# Assignment 1 - Linear algebra

In [14]:
# 1- Write a NumPy program to test whether none of the elements of a given array is zero
import numpy as np
x = np.array([1, 2, 3, 4])
print(np.all(x))

True


In [13]:
# 2- Write a NumPy program to test whether any of the elements of a given array is non-zero.
x = np.array([1, 0, 0, 0])
print(np.any(x))

True


In [15]:
# 3- Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


In [16]:
# 4- Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives
x=np.zeros(10)
print(x)
y=np.ones(10)
print(y)
z=np.ones(10)*5
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [17]:
# 5- Write a NumPy program to create an array of the integers from 30 to70
x=np.arange(30,71)
print(x)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [18]:
# 6- Write a NumPy program to create a 3x3 identity matrix
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# 7- Write a NumPy program to generate a random number between 0 and 1 
rand_num = np.random.normal(0,1,1)
print(rand_num)

[0.32171161]


In [20]:
# 8- Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution
rand_num = np.random.normal(0,1,15)
print(rand_num)

[ 1.41685043  0.31523429  0.04537075  0.34606386 -1.00159117  1.45208892
 -0.33754363 -1.38145357  0.20931196 -1.95734386  0.09391357 -0.25526299
 -0.30266935 -1.74075834  1.27240188]


In [26]:
# 9- Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last
v = np.arange(15,55)
print(v[1:])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [27]:
# 10- Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10
x = np.random.randint(0, 11, 5)
print(x)

[ 9 10  4  7  3]


In [28]:
# 11- Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [29]:
# 12- Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [30]:
# 13-  Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [32]:
# 14- Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.
import os
x = np.arange(10)
y = np.arange(11, 20)
np.savez('temp_arra.npz', x=x, y=y)
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [2]:
# 15- Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values
import numpy as np  
x = np.random.seed(10)
print(np.random.rand(40))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


In [4]:
# 16- rite a NumPy program to extract all numbers from a given array which are less and greater than a specified number.
nums = np.array([[6, 4, 8],
              [4, 5, 7],
              [2, 3, 10]])
n = 5
print(nums[nums > n])
print(nums[nums < n])

[ 6  8  7 10]
[4 4 2 3]
